version: '3'
services:
  db:
    image: postgres:9.4.1
    ports:
      - "5432:5432"
    env_file:
      - .env.docker

  redis:
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - .env.docker

  web:
    build: .
    command: bin/rails server -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    volumes:
      - .:/shiori
    env_file:
      - .env.docker
