version: '3'
services:
  db:
    image: postgres:9.4.1
    volumes:
      - shioridata:/var/lib/postgresql/data
    env_file:
      - .env.docker

  redis:
    image: redis
    volumes:
      - shioriredisdata:/data
    env_file:
      - .env.docker

  web:
    tty: true
    stdin_open: true
    build: .
    command: bin/rails server -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/shiori
    env_file:
      - .env.docker

  sidekiq:
    build: .
    command: sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - redis
    volumes:
      - .:/shiori
    env_file:
      - .env.docker

volumes:
  shioridata:
  shioriredisdata:
